services:
  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - mirror-data:/home/generic/yocto-mirror
    networks:
      - internal
    expose:
      - "5000"
    environment:
      - SERVE=https://github.com/aurelienizl/test
    stop_signal: SIGTERM  # or SIGINT
    stop_grace_period: 1h # 1 hour

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - mirror-data:/yocto-mirror
    depends_on:
      - python
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  mirror-data:
